[package]
name = "ccsds-space-packet"
version = "0.1.0"
edition = "2024"

[features]
nightly = []

[dev-dependencies]
rand = { version = "0.9.1", features = ["small_rng"], default-features = false }

[profile.dev] # Changes needed to support no_panic
opt-level = 2
debug-assertions = false
overflow-checks = false

[dependencies]
allocator-api2 = "0.3.0"
zerocopy = { version = "0.8.26", features = ["derive"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
